configuration:
  - mingw53_32
  - msvc2017_64

environment:
  PROJECT_DIR: C:\projects\cutehmi
  matrix:
    - QBS_CONFIG: debug
    - QBS_CONFIG: release

image:
- Visual Studio 2017

install:
# - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\Tools\QtCreator\bin\

for:
-
  matrix:
    only:
      - configuration: mingw53_32
  environment:
    QT_PATH: C:\Qt\5.11.2\mingw53_32
  before_build:
    - set PATH=%QT_PATH%\bin;C:\Qt\Tools\QtCreator\bin\;%PATH%
    - qtenv2.bat
    - qbs setup-toolchains --detect
    - qbs setup-qt --detect
    - cd %PROJECT_DIR%
  build_script:
    - qbs build -f CuteHMI.qbs -d build --command-echo-mode command-line profile:qt-5-11-2 config:%QBS_CONFIG%
-
  matrix:
    only:
      - configuration: msvc2017_64
  environment:
    QT_PATH: C:\Qt\5.11.2\msvc2017_64
  before_build:
    - set PATH=%QT_PATH%\bin;C:\Qt\Tools\QtCreator\bin\;%PATH%
    - qtenv2.bat
    - qbs setup-toolchains --detect
    - qbs setup-qt --detect
    - cd %PROJECT_DIR%
  build_script:
    - qbs build -f CuteHMI.qbs -d build --command-echo-mode command-line profile:qt-5-11-2 config:%QBS_CONFIG%
      
